"""Render a bot-detection evaluation as Markdown."""

from __future__ import annotations

from typing import Any

from brisca.detection.model import FPR_BUDGET, HELD_OUT_STYLE


def _pct(x: float) -> str:
    return f"{100 * x:.1f}%"


def render(report: dict[str, Any]) -> str:
    main = report["main"]
    lines = [
        "# Bot detection: evaluation report",
        "",
        "Generated by `brisca detect train`. All data is **synthetic** "
        "(see `brisca.detection.simulate` and the model card).",
        "",
        f"- {report['players']:,} players, {report['sessions']:,} sessions, "
        f"{_pct(report['bot_share'])} bot sessions",
        "- 5-fold cross-validation grouped by player; the operating point flags at most "
        f"{_pct(FPR_BUDGET)} of human sessions",
        f"- `{HELD_OUT_STYLE}` bots are never trained on (unseen-adversary test)",
        "",
        "## Headline metrics (bot styles seen in training)",
        "",
        "| Model | ROC-AUC | PR-AUC | Recall at 1% FPR |",
        "| --- | ---: | ---: | ---: |",
    ]
    rows = {
        "XGBoost, all features": main,
        **{f"XGBoost, {k}": v for k, v in report["ablations"].items()},
        "Logistic regression, all features": report["logistic_baseline"],
    }
    for name, m in rows.items():
        lines.append(
            f"| {name} | {m['roc_auc']:.3f} | {m['pr_auc']:.3f} | {_pct(m['recall_at_1pct_fpr'])} |"
        )

    lines += [
        "",
        f"Brier score: {main['brier_raw']:.4f} raw, {main['brier_calibrated']:.4f} after "
        "isotonic calibration.",
        "",
        "## Recall by bot type, at the 1% FPR operating point",
        "",
        "| Timing style | Recall |",
        "| --- | ---: |",
    ]
    for style, recall in report["recall_by_style"].items():
        note = " (never trained on)" if style == HELD_OUT_STYLE else ""
        lines.append(f"| `{style}`{note} | {_pct(recall)} |")
    lines += ["", "| Bot policy | Recall (seen styles) |", "| --- | ---: |"]
    for policy, recall in report["recall_by_policy"].items():
        lines.append(f"| `{policy}` | {_pct(recall)} |")

    lines += [
        "",
        "## False positives by human skill",
        "",
        "| Human skill | Sessions wrongly flagged |",
        "| --- | ---: |",
    ]
    for band, fpr in report["human_fpr_by_skill"].items():
        lines.append(f"| {band} | {_pct(fpr)} |")

    lines += [
        "",
        "## Calibration (seen styles, out of fold)",
        "",
        "| Predicted probability | Sessions | Mean predicted | Observed bot rate |",
        "| --- | ---: | ---: | ---: |",
    ]
    for row in report["reliability"]:
        lines.append(
            f"| {row['bin']} | {row['sessions']} | {row['predicted']:.3f} | {row['observed']:.3f} |"
        )

    lines += [
        "",
        "## Most influential features (mean |SHAP|, log-odds)",
        "",
        "| Feature | Mean \\|SHAP\\| |",
        "| --- | ---: |",
    ]
    for feature, value in list(report["feature_importance"].items())[:10]:
        lines.append(f"| `{feature}` | {value:.3f} |")
    return "\n".join(lines) + "\n"
