"""``brisca`` command line: run tournaments and publish leaderboards."""

from __future__ import annotations

import argparse
import logging
import time
from pathlib import Path

from brisca.report import leaderboard, update_readme
from brisca.store import ResultsStore
from brisca.tournament import TournamentConfig, run_tournament

log = logging.getLogger("brisca")
DEFAULT_DB = Path("results/brisca.duckdb")


def _tournament(args: argparse.Namespace) -> None:
    config = TournamentConfig.from_toml(args.config)
    pairs = len(config.agents) * (len(config.agents) - 1) // 2
    log.info(
        "%d agents, %d pairings, %d games", len(config.agents), pairs, pairs * config.deals * 2
    )
    start = time.perf_counter()
    records = run_tournament(config, workers=args.workers)
    store = ResultsStore(args.db)
    tournament_id = store.save(config, records)
    store.close()
    log.info(
        "tournament %d saved to %s in %.0fs", tournament_id, args.db, time.perf_counter() - start
    )


def _report(args: argparse.Namespace) -> None:
    store = ResultsStore(args.db)
    tournament = args.tournament or store.latest_tournament()
    content = leaderboard(store, tournament, anchor=args.anchor, bootstrap=args.bootstrap)
    if args.export_games:
        store.export_games(tournament, args.export_games)
    store.close()
    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(content)
    if args.readme:
        update_readme(args.readme, content)
    if not args.out and not args.readme:
        print(content)


def _toml_value(value: object) -> str:
    if isinstance(value, bool):
        return str(value).lower()
    if isinstance(value, str):
        return f'"{value}"'
    return repr(value)


def _tune(args: argparse.Namespace) -> None:
    from brisca.mlops.tuning import tune

    kwargs = (
        {"deals": args.deals}
        if args.target == "heuristic"
        else {"total_steps": args.steps, "eval_deals": args.deals}
    )
    study = tune(args.target, args.trials, args.storage, workers=args.workers, **kwargs)
    header = (
        f"# Best of {len(study.trials)} Optuna trials (study '{study.study_name}'), "
        f"objective {study.best_value:.4f}. Generated by 'brisca tune {args.target}'.\n"
    )
    if args.target == "heuristic":
        from brisca.mlops.tuning import heuristic_holdout

        holdout = heuristic_holdout(study, deals=args.deals * 5)
        log.info("held-out score %.4f (in-search %.4f)", holdout, study.best_value)
        header += f"# Held-out score on {args.deals * 5} unseen deals: {holdout:.4f}.\n"
    body = "".join(f"{k} = {_toml_value(v)}\n" for k, v in sorted(study.best_params.items()))
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(header + body)
    log.info("wrote %s", args.out)


def _promote(args: argparse.Namespace) -> None:
    from brisca.mlops.promotion import promote
    from brisca.mlops.tracking import configure

    configure("promotion")
    model_uri = args.model
    if Path(model_uri).is_file():  # a local checkpoint: log it to MLflow first
        import mlflow

        from brisca.mlops.tracking import git_tags, log_policy
        from brisca.rl import load_checkpoint

        configure("imported")
        model, metadata = load_checkpoint(model_uri)
        with mlflow.start_run(run_name=Path(model_uri).stem, tags=git_tags()):
            mlflow.log_param("source", model_uri)
            model_uri = log_policy(model, metadata)
    decision = promote(model_uri, deals=args.deals, alpha=args.alpha)
    print(f"v{decision.version} promoted={decision.promoted}: {decision.reason}")


def _detect_simulate(args: argparse.Namespace) -> None:
    from brisca.detection.simulate import simulate_population

    summary = simulate_population(
        args.db, players=args.players, bot_rate=args.bot_rate, seed=args.seed, workers=args.workers
    )
    log.info("simulated %s into %s", summary, args.db)


def _detect_train(args: argparse.Namespace) -> None:
    from brisca.detection.features import load_dataset
    from brisca.detection.model import evaluate
    from brisca.detection.report import render

    report = evaluate(load_dataset(args.db), seed=args.seed, ship=args.features)
    detector = report.pop("detector")
    detector.save(args.model)
    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(render(report))
    log.info("saved detector to %s and report to %s", args.model, args.report)
    if args.mlflow:
        import mlflow

        from brisca.mlops.tracking import configure, git_tags

        configure("bot-detection")
        with mlflow.start_run(tags=git_tags()):
            mlflow.log_params({"db": str(args.db), "seed": args.seed, "features": args.features})
            mlflow.log_metrics(report["main"])
            shipped = {k: v for k, v in report["shipped"].items() if isinstance(v, float)}
            mlflow.log_metrics({f"shipped_{k}": v for k, v in shipped.items()})
            mlflow.log_metrics({f"recall_{k}": v for k, v in report["recall_by_style"].items()})
            mlflow.log_artifacts(str(args.model), artifact_path="detector")
            mlflow.log_artifact(str(args.report))


def _llm_benchmark(args: argparse.Namespace) -> None:
    import json

    from brisca.agents import make_agent
    from brisca.arena import play_match
    from brisca.llm.agent import PRICES, LLMAgent
    from brisca.ratings import wilson_interval

    # ~17 non-forced decisions per game; input ~1.2k tokens, output incl. thinking ~0.6k.
    decisions = args.deals * 2 * 17
    price_in, price_out = PRICES.get(args.model, (0.0, 0.0))
    estimate = decisions * (1200 * price_in + 600 * price_out) / 1e6
    print(
        f"{args.deals * 2} games vs {args.opponent}, about {decisions} API calls to "
        f"{args.model} at effort={args.effort}: roughly ${estimate:.2f} (rough estimate)."
    )
    if not args.yes:
        print("Re-run with --yes to spend this.")
        return

    agent = LLMAgent(model=args.model, effort=args.effort)
    result = play_match(agent, make_agent(args.opponent), deals=args.deals, seed=args.seed)
    lo, hi = wilson_interval(result.score, result.games)
    summary = {
        "model": args.model,
        "effort": args.effort,
        "opponent": args.opponent,
        "games": result.games,
        "score": result.score,
        "score_95ci": [lo, hi],
        "points_per_game": result.points_for / result.games,
        "fallback_rate": agent.fallback_rate,
        "stats": dict(agent.stats),
        "cost_usd": round(agent.cost_usd(), 4),
        "cost_per_game_usd": round(agent.cost_usd() / result.games, 4),
    }
    print(json.dumps(summary, indent=2))
    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(json.dumps(summary, indent=2) + "\n")


def _stream_produce(args: argparse.Namespace) -> None:
    from brisca import streaming

    streaming.ensure_topics(args.bootstrap, [args.topic])
    events = (
        streaming.events_from_db(args.db)
        if args.db
        else streaming.live_events(bot_rate=args.bot_rate, seed=args.seed)
    )
    sent = streaming.produce(
        events, streaming.kafka_producer(args.bootstrap), args.topic, args.rate, args.limit
    )
    log.info("produced %d events to %s", sent, args.topic)


def _stream_score(args: argparse.Namespace) -> None:
    from prometheus_client import REGISTRY, start_http_server

    from brisca import streaming
    from brisca.detection.model import Detector

    streaming.ensure_topics(args.bootstrap, [args.topic, args.out_topic])
    scorer = streaming.Scorer(
        Detector.load(args.model),
        streaming.kafka_producer(args.bootstrap),
        out_topic=args.out_topic,
        registry=REGISTRY,
    )
    start_http_server(args.metrics_port)
    consumer = streaming.kafka_consumer(args.bootstrap, args.topic, args.group)
    log.info("scoring %s -> %s (metrics on :%d)", args.topic, args.out_topic, args.metrics_port)
    try:
        scorer.run(consumer)
    finally:
        consumer.close()


def main(argv: list[str] | None = None) -> None:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(message)s")
    parser = argparse.ArgumentParser(prog="brisca", description=__doc__)
    sub = parser.add_subparsers(required=True)

    run = sub.add_parser("tournament", help="run a round-robin tournament from a TOML config")
    run.add_argument("config", type=Path)
    run.add_argument("--db", type=Path, default=DEFAULT_DB)
    run.add_argument("--workers", type=int, default=None)
    run.set_defaults(func=_tournament)

    rep = sub.add_parser("report", help="print or publish the leaderboard for a tournament")
    rep.add_argument("--db", type=Path, default=DEFAULT_DB)
    rep.add_argument("--tournament", type=int, default=None, help="defaults to the latest")
    rep.add_argument("--anchor", default="random", help="agent rated 0 (default: random)")
    rep.add_argument("--bootstrap", type=int, default=500)
    rep.add_argument("--out", type=Path, default=None)
    rep.add_argument("--readme", type=Path, default=None)
    rep.add_argument("--export-games", type=Path, default=None, help="write games to Parquet")
    rep.set_defaults(func=_report)

    tune = sub.add_parser("tune", help="Optuna search for heuristic or PPO hyperparameters")
    tune.add_argument("target", choices=["heuristic", "ppo"])
    tune.add_argument("--trials", type=int, default=50)
    tune.add_argument("--workers", type=int, default=1)
    tune.add_argument("--deals", type=int, default=100, help="evaluation deals per trial")
    tune.add_argument("--steps", type=int, default=400_000, help="PPO training steps per trial")
    tune.add_argument("--storage", default="sqlite:///results/optuna.db")
    tune.add_argument("--out", type=Path, required=True, help="TOML file for the best settings")
    tune.set_defaults(func=_tune)

    prom = sub.add_parser(
        "promote", help="register a policy and make it champion if it beats the current one"
    )
    prom.add_argument("model", help="MLflow model URI or local checkpoint path")
    prom.add_argument("--deals", type=int, default=300)
    prom.add_argument("--alpha", type=float, default=0.05)
    prom.set_defaults(func=_promote)

    detect = sub.add_parser("detect", help="bot detection from gameplay telemetry")
    detect_sub = detect.add_subparsers(required=True)
    sim = detect_sub.add_parser("simulate", help="simulate a population's telemetry")
    sim.add_argument("--players", type=int, default=2000)
    sim.add_argument("--bot-rate", type=float, default=0.15)
    sim.add_argument("--db", type=Path, default=Path("data/telemetry.duckdb"))
    sim.add_argument("--seed", type=int, default=0)
    sim.add_argument("--workers", type=int, default=None)
    sim.set_defaults(func=_detect_simulate)
    fit = detect_sub.add_parser("train", help="evaluate, then fit and save the detector")
    fit.add_argument("--db", type=Path, default=Path("data/telemetry.duckdb"))
    fit.add_argument("--model", type=Path, default=Path("models/bot-detector"))
    fit.add_argument("--report", type=Path, default=Path("docs/bot-detection-report.md"))
    fit.add_argument("--seed", type=int, default=0)
    fit.add_argument(
        "--features",
        choices=["decision", "timing", "all"],
        default="decision",
        help="feature set of the saved detector (default: robust decision features)",
    )
    fit.add_argument("--mlflow", action="store_true", help="log the run to MLflow")
    fit.set_defaults(func=_detect_train)

    llm = sub.add_parser("llm", help="Claude-powered agent")
    llm_sub = llm.add_subparsers(required=True)
    bench = llm_sub.add_parser("benchmark", help="duplicate match: Claude vs a reference agent")
    bench.add_argument("--opponent", default="heuristic")
    bench.add_argument("--deals", type=int, default=10)
    bench.add_argument("--model", default="claude-opus-5-5")
    bench.add_argument("--effort", choices=["low", "medium", "high", "xhigh", "max"], default="low")
    bench.add_argument("--seed", type=int, default=0)
    bench.add_argument("--out", type=Path, default=Path("results/llm-benchmark.json"))
    bench.add_argument("--yes", action="store_true", help="confirm the API spend")
    bench.set_defaults(func=_llm_benchmark)

    stream = sub.add_parser("stream", help="real-time bot scoring over Kafka")
    stream_sub = stream.add_subparsers(required=True)
    prod = stream_sub.add_parser("produce", help="publish gameplay events")
    prod.add_argument("--bootstrap", default="localhost:19092")
    prod.add_argument("--topic", default="brisca.events")
    prod.add_argument(
        "--db", type=Path, default=None, help="replay telemetry instead of simulating"
    )
    prod.add_argument("--rate", type=float, default=200.0, help="events per second (0: unpaced)")
    prod.add_argument("--limit", type=int, default=None)
    prod.add_argument("--bot-rate", type=float, default=0.15)
    prod.add_argument("--seed", type=int, default=0)
    prod.set_defaults(func=_stream_produce)
    score = stream_sub.add_parser("score", help="consume events and publish bot scores")
    score.add_argument("--bootstrap", default="localhost:19092")
    score.add_argument("--topic", default="brisca.events")
    score.add_argument("--out-topic", default="brisca.bot-scores")
    score.add_argument("--group", default="bot-scorer")
    score.add_argument("--model", type=Path, default=Path("models/bot-detector"))
    score.add_argument("--metrics-port", type=int, default=9100)
    score.set_defaults(func=_stream_score)

    args = parser.parse_args(argv)
    args.func(args)


if __name__ == "__main__":
    main()
