"""``brisca`` command line: run tournaments and publish leaderboards."""

from __future__ import annotations

import argparse
import logging
import time
from pathlib import Path

from brisca.report import leaderboard, update_readme
from brisca.store import ResultsStore
from brisca.tournament import TournamentConfig, run_tournament

log = logging.getLogger("brisca")
DEFAULT_DB = Path("results/brisca.duckdb")


def _tournament(args: argparse.Namespace) -> None:
    config = TournamentConfig.from_toml(args.config)
    pairs = len(config.agents) * (len(config.agents) - 1) // 2
    log.info(
        "%d agents, %d pairings, %d games", len(config.agents), pairs, pairs * config.deals * 2
    )
    start = time.perf_counter()
    records = run_tournament(config, workers=args.workers)
    store = ResultsStore(args.db)
    tournament_id = store.save(config, records)
    store.close()
    log.info(
        "tournament %d saved to %s in %.0fs", tournament_id, args.db, time.perf_counter() - start
    )


def _report(args: argparse.Namespace) -> None:
    store = ResultsStore(args.db)
    tournament = args.tournament or store.latest_tournament()
    content = leaderboard(store, tournament, anchor=args.anchor, bootstrap=args.bootstrap)
    if args.export_games:
        store.export_games(tournament, args.export_games)
    store.close()
    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(content)
    if args.readme:
        update_readme(args.readme, content)
    if not args.out and not args.readme:
        print(content)


def _toml_value(value: object) -> str:
    if isinstance(value, bool):
        return str(value).lower()
    if isinstance(value, str):
        return f'"{value}"'
    return repr(value)


def _tune(args: argparse.Namespace) -> None:
    from brisca.mlops.tuning import tune

    kwargs = (
        {"deals": args.deals}
        if args.target == "heuristic"
        else {"total_steps": args.steps, "eval_deals": args.deals}
    )
    study = tune(args.target, args.trials, args.storage, workers=args.workers, **kwargs)
    header = (
        f"# Best of {len(study.trials)} Optuna trials (study '{study.study_name}'), "
        f"objective {study.best_value:.4f}. Generated by 'brisca tune {args.target}'.\n"
    )
    if args.target == "heuristic":
        from brisca.mlops.tuning import heuristic_holdout

        holdout = heuristic_holdout(study, deals=args.deals * 5)
        log.info("held-out score %.4f (in-search %.4f)", holdout, study.best_value)
        header += f"# Held-out score on {args.deals * 5} unseen deals: {holdout:.4f}.\n"
    body = "".join(f"{k} = {_toml_value(v)}\n" for k, v in sorted(study.best_params.items()))
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(header + body)
    log.info("wrote %s", args.out)


def _promote(args: argparse.Namespace) -> None:
    from brisca.mlops.promotion import promote
    from brisca.mlops.tracking import configure

    configure("promotion")
    model_uri = args.model
    if Path(model_uri).is_file():  # a local checkpoint: log it to MLflow first
        import mlflow

        from brisca.mlops.tracking import git_tags, log_policy
        from brisca.rl import load_checkpoint

        configure("imported")
        model, metadata = load_checkpoint(model_uri)
        with mlflow.start_run(run_name=Path(model_uri).stem, tags=git_tags()):
            mlflow.log_param("source", model_uri)
            model_uri = log_policy(model, metadata)
    decision = promote(model_uri, deals=args.deals, alpha=args.alpha)
    print(f"v{decision.version} promoted={decision.promoted}: {decision.reason}")


def _detect_simulate(args: argparse.Namespace) -> None:
    from brisca.detection.simulate import simulate_population

    summary = simulate_population(
        args.db, players=args.players, bot_rate=args.bot_rate, seed=args.seed, workers=args.workers
    )
    log.info("simulated %s into %s", summary, args.db)


def _detect_train(args: argparse.Namespace) -> None:
    from brisca.detection.features import load_dataset
    from brisca.detection.model import evaluate
    from brisca.detection.report import render

    report = evaluate(load_dataset(args.db), seed=args.seed, ship=args.features)
    detector = report.pop("detector")
    detector.save(args.model)
    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(render(report))
    log.info("saved detector to %s and report to %s", args.model, args.report)
    if args.mlflow:
        import mlflow

        from brisca.mlops.tracking import configure, git_tags

        configure("bot-detection")
        with mlflow.start_run(tags=git_tags()):
            mlflow.log_params({"db": str(args.db), "seed": args.seed, "features": args.features})
            mlflow.log_metrics(report["main"])
            shipped = {k: v for k, v in report["shipped"].items() if isinstance(v, float)}
            mlflow.log_metrics({f"shipped_{k}": v for k, v in shipped.items()})
            mlflow.log_metrics({f"recall_{k}": v for k, v in report["recall_by_style"].items()})
            mlflow.log_artifacts(str(args.model), artifact_path="detector")
            mlflow.log_artifact(str(args.report))


def main(argv: list[str] | None = None) -> None:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(message)s")
    parser = argparse.ArgumentParser(prog="brisca", description=__doc__)
    sub = parser.add_subparsers(required=True)

    run = sub.add_parser("tournament", help="run a round-robin tournament from a TOML config")
    run.add_argument("config", type=Path)
    run.add_argument("--db", type=Path, default=DEFAULT_DB)
    run.add_argument("--workers", type=int, default=None)
    run.set_defaults(func=_tournament)

    rep = sub.add_parser("report", help="print or publish the leaderboard for a tournament")
    rep.add_argument("--db", type=Path, default=DEFAULT_DB)
    rep.add_argument("--tournament", type=int, default=None, help="defaults to the latest")
    rep.add_argument("--anchor", default="random", help="agent rated 0 (default: random)")
    rep.add_argument("--bootstrap", type=int, default=500)
    rep.add_argument("--out", type=Path, default=None)
    rep.add_argument("--readme", type=Path, default=None)
    rep.add_argument("--export-games", type=Path, default=None, help="write games to Parquet")
    rep.set_defaults(func=_report)

    tune = sub.add_parser("tune", help="Optuna search for heuristic or PPO hyperparameters")
    tune.add_argument("target", choices=["heuristic", "ppo"])
    tune.add_argument("--trials", type=int, default=50)
    tune.add_argument("--workers", type=int, default=1)
    tune.add_argument("--deals", type=int, default=100, help="evaluation deals per trial")
    tune.add_argument("--steps", type=int, default=400_000, help="PPO training steps per trial")
    tune.add_argument("--storage", default="sqlite:///results/optuna.db")
    tune.add_argument("--out", type=Path, required=True, help="TOML file for the best settings")
    tune.set_defaults(func=_tune)

    prom = sub.add_parser(
        "promote", help="register a policy and make it champion if it beats the current one"
    )
    prom.add_argument("model", help="MLflow model URI or local checkpoint path")
    prom.add_argument("--deals", type=int, default=300)
    prom.add_argument("--alpha", type=float, default=0.05)
    prom.set_defaults(func=_promote)

    detect = sub.add_parser("detect", help="bot detection from gameplay telemetry")
    detect_sub = detect.add_subparsers(required=True)
    sim = detect_sub.add_parser("simulate", help="simulate a population's telemetry")
    sim.add_argument("--players", type=int, default=2000)
    sim.add_argument("--bot-rate", type=float, default=0.15)
    sim.add_argument("--db", type=Path, default=Path("data/telemetry.duckdb"))
    sim.add_argument("--seed", type=int, default=0)
    sim.add_argument("--workers", type=int, default=None)
    sim.set_defaults(func=_detect_simulate)
    fit = detect_sub.add_parser("train", help="evaluate, then fit and save the detector")
    fit.add_argument("--db", type=Path, default=Path("data/telemetry.duckdb"))
    fit.add_argument("--model", type=Path, default=Path("models/bot-detector"))
    fit.add_argument("--report", type=Path, default=Path("docs/bot-detection-report.md"))
    fit.add_argument("--seed", type=int, default=0)
    fit.add_argument(
        "--features",
        choices=["decision", "timing", "all"],
        default="decision",
        help="feature set of the saved detector (default: robust decision features)",
    )
    fit.add_argument("--mlflow", action="store_true", help="log the run to MLflow")
    fit.set_defaults(func=_detect_train)

    args = parser.parse_args(argv)
    args.func(args)


if __name__ == "__main__":
    main()
