"""``brisca`` command line: run tournaments and publish leaderboards."""

from __future__ import annotations

import argparse
import logging
import time
from pathlib import Path

from brisca.report import leaderboard, update_readme
from brisca.store import ResultsStore
from brisca.tournament import TournamentConfig, run_tournament

log = logging.getLogger("brisca")
DEFAULT_DB = Path("results/brisca.duckdb")


def _tournament(args: argparse.Namespace) -> None:
    config = TournamentConfig.from_toml(args.config)
    pairs = len(config.agents) * (len(config.agents) - 1) // 2
    log.info(
        "%d agents, %d pairings, %d games", len(config.agents), pairs, pairs * config.deals * 2
    )
    start = time.perf_counter()
    records = run_tournament(config, workers=args.workers)
    store = ResultsStore(args.db)
    tournament_id = store.save(config, records)
    store.close()
    log.info(
        "tournament %d saved to %s in %.0fs", tournament_id, args.db, time.perf_counter() - start
    )


def _report(args: argparse.Namespace) -> None:
    store = ResultsStore(args.db)
    tournament = args.tournament or store.latest_tournament()
    content = leaderboard(store, tournament, anchor=args.anchor, bootstrap=args.bootstrap)
    if args.export_games:
        store.export_games(tournament, args.export_games)
    store.close()
    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(content)
    if args.readme:
        update_readme(args.readme, content)
    if not args.out and not args.readme:
        print(content)


def _toml_value(value: object) -> str:
    if isinstance(value, bool):
        return str(value).lower()
    if isinstance(value, str):
        return f'"{value}"'
    return repr(value)


def _tune(args: argparse.Namespace) -> None:
    from brisca.mlops.tuning import tune

    kwargs = (
        {"deals": args.deals}
        if args.target == "heuristic"
        else {"total_steps": args.steps, "eval_deals": args.deals}
    )
    study = tune(args.target, args.trials, args.storage, workers=args.workers, **kwargs)
    header = (
        f"# Best of {len(study.trials)} Optuna trials (study '{study.study_name}'), "
        f"objective {study.best_value:.4f}. Generated by 'brisca tune {args.target}'.\n"
    )
    if args.target == "heuristic":
        from brisca.mlops.tuning import heuristic_holdout

        holdout = heuristic_holdout(study, deals=args.deals * 5)
        log.info("held-out score %.4f (in-search %.4f)", holdout, study.best_value)
        header += f"# Held-out score on {args.deals * 5} unseen deals: {holdout:.4f}.\n"
    body = "".join(f"{k} = {_toml_value(v)}\n" for k, v in sorted(study.best_params.items()))
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(header + body)
    log.info("wrote %s", args.out)


def _promote(args: argparse.Namespace) -> None:
    from brisca.mlops.promotion import promote
    from brisca.mlops.tracking import configure

    configure("promotion")
    decision = promote(args.model_uri, deals=args.deals, alpha=args.alpha)
    print(f"v{decision.version} promoted={decision.promoted}: {decision.reason}")


def main(argv: list[str] | None = None) -> None:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(message)s")
    parser = argparse.ArgumentParser(prog="brisca", description=__doc__)
    sub = parser.add_subparsers(required=True)

    run = sub.add_parser("tournament", help="run a round-robin tournament from a TOML config")
    run.add_argument("config", type=Path)
    run.add_argument("--db", type=Path, default=DEFAULT_DB)
    run.add_argument("--workers", type=int, default=None)
    run.set_defaults(func=_tournament)

    rep = sub.add_parser("report", help="print or publish the leaderboard for a tournament")
    rep.add_argument("--db", type=Path, default=DEFAULT_DB)
    rep.add_argument("--tournament", type=int, default=None, help="defaults to the latest")
    rep.add_argument("--anchor", default="random", help="agent rated 0 (default: random)")
    rep.add_argument("--bootstrap", type=int, default=500)
    rep.add_argument("--out", type=Path, default=None)
    rep.add_argument("--readme", type=Path, default=None)
    rep.add_argument("--export-games", type=Path, default=None, help="write games to Parquet")
    rep.set_defaults(func=_report)

    tune = sub.add_parser("tune", help="Optuna search for heuristic or PPO hyperparameters")
    tune.add_argument("target", choices=["heuristic", "ppo"])
    tune.add_argument("--trials", type=int, default=50)
    tune.add_argument("--workers", type=int, default=1)
    tune.add_argument("--deals", type=int, default=100, help="evaluation deals per trial")
    tune.add_argument("--steps", type=int, default=400_000, help="PPO training steps per trial")
    tune.add_argument("--storage", default="sqlite:///results/optuna.db")
    tune.add_argument("--out", type=Path, required=True, help="TOML file for the best settings")
    tune.set_defaults(func=_tune)

    prom = sub.add_parser("promote", help="register a logged policy; promote if it beats champion")
    prom.add_argument("model_uri")
    prom.add_argument("--deals", type=int, default=300)
    prom.add_argument("--alpha", type=float, default=0.05)
    prom.set_defaults(func=_promote)

    args = parser.parse_args(argv)
    args.func(args)


if __name__ == "__main__":
    main()
